language: node_js
cache:
  directories:
  - node_modules
node_js:
- 6
install:
- npm install
script:
- npm run test:ci
notifications:
  email: false
  slack:
    rooms:
      secure: RoL35IvEwGK83tRnlXnZbOplrNzYEvPjaY6zJONc98hNrdIKEWmWO8iYAOQnMCuI7lZNw3wXxUVL8lOWFDatUhChIuUG1lt5t0cqn1OHl9kFfxTCo3zJB0oCJbVBck78PKdfnapMYVWyOR2wVdOy8G94BPxZZ2rT0/bp1/jg1t3puZJUR3drYOQJCvoyYqs+gqMp2GnQFY2dpl+stl9FToju1wQa0C9GH+5EOtiLPuHjrSJsbLet0qn/qhxhaYuG7B34zYQOcRyLamVcypg1pG40u1NsS0uT1ex06hZqHA1n+km4CFJY45PErRIKJ4pYjT6sBAzMRMO0n0hIg2k2btOZdoHQf9AMoaLdaYqxrkSFs0ay27Ax1ST0rJBN0BlZ24gyJgFCT+Jnzo5ro1fUF+4wY8kYr6ApSGuw7gftH4OViHA05Gye2/yuW5YXr2fyugUX7iKDt9eNtNJb1BepV6aJMC9TtQD9kOyIkt+W0EAJPQ9nBQL7UorCobA6s7wNnU2bagH6PmHoAw9RGFo+iOiMFN+Hdd+S8S8M25q9/UD/NuMLPIZckMCbIb973n3qfKvVo5mqE8S60oHTmYS01WsQUruF1r6x+kP2ZdcAqhOrA9unJoTgyo4U5yXZD3VDuPUrM8jwD7fq64Zlz98LHnMzK3ilGg12wTtXSOC51SE=
